
package au.com.pnscustomer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "pns-customer-service", targetNamespace = "http://www.specsavers.nl/pns/pns-customer-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PnsCustomerService {


    /**
     * 
     * @param pnsCustomerRequest
     * @return
     *     returns au.com.pnscustomer.PNSCustomerResponse
     * @throws PNSCustomerFaultMessage
     */
    @WebMethod(operationName = "PNSCustomer", action = "http://www.specsavers.nl/pns/pns-customer-service/PNSCustomer")
    @WebResult(name = "PNSCustomerResponseMessage", targetNamespace = "http://www.specsavers.nl/pns/pns-customer-service/", partName = "pnsCustomerResponse")
    public PNSCustomerResponse pnsCustomer(
        @WebParam(name = "PNSCustomerRequestMessage", targetNamespace = "http://www.specsavers.nl/pns/pns-customer-service/", partName = "pnsCustomerRequest")
        PNSCustomerRequest pnsCustomerRequest)
        throws PNSCustomerFaultMessage
    ;

}
